# Generated by Django 5.0.1 on 2025-06-04 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
