# Generated by Django 5.0.1 on 2025-06-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_roles',
            field=models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('agent', 'Agent')], default='customer', max_length=50, null=True),
        ),
    ]
