# Generated by Django 5.2.1 on 2025-06-05 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_user_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='vendorproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorproduct_images', to='ecom.vendorproduct'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='form_type',
            field=models.CharField(blank=True, choices=[('query', 'QUERY'), ('issue', 'ISSUE'), ('feedback', 'FEEDBACK')], max_length=20, null=True),
        ),
    ]
